trainingInput:
  scaleTier: CUSTOM
  masterType: n1-standard-4
  masterConfig:
    acceleratorConfig:
      count: 8
      type: NVIDIA_TESLA_K80
  # workerCount: 3
  # workerType: n1-standard-4
  # workerConfig:
  #   acceleratorConfig:
  #     count: 4
  #     type: NVIDIA_TESLA_K80
  # type: NVIDIA_TESLA_T4
  # hyperparameters:
  #     goal: MINIMIZE
  #     hyperparameterMetricTag: losses/total_loss
  #     maxTrials: 5
  #     maxParallelTrials: 1
  #     enableTrialEarlyStopping: True
  #     params:
