NUMBER_OF_BBOXES = "number_of_bboxes"
BBOX_SIZE = 8
BBOXES = "bboxes"
HEIGHT = "height"
IMAGE = "image"
IMAGE_NAME = "image_name"
LABEL = "label"
TAGS = "tags"
RESIZE_LENGTH = 1280
WIDTH = "width"
KERNELS = "kernels"
TRAINING_MASK = "training_mask"
TEXT = "text"
CROP_SIZE = 640
MIN_SCALE = 0.4
KERNEL_NUM = 7
MEAN_RGB = [0.485, 0.456, 0.406]
STDDEV_RGB = [0.229, 0.224, 0.225]
MAX_ROTATION_ANGLE = 10

